import web3 from './web3';

const address = '0x5A9D2ee589c23FaC6b510bA3EaeaBBBE1d9563f0';

const abi = [ { inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
    constant: undefined,
    payable: undefined,
    signature: 'constructor' },
  { inputs: [ [Object] ],
    name: 'addStatus',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x30f23c8b' },
  { inputs: [ [Object], [Object] ],
    name: 'changeTaskAuthor',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xa23d1789' },
  { inputs: [ [Object], [Object] ],
    name: 'changeTaskName',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xdba77555' },
  { inputs: [ [Object], [Object] ],
    name: 'changeTaskStatus',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x69616ece' },
  { inputs: [ [Object], [Object], [Object] ],
    name: 'createTask',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x41a4e30a' },
  { inputs: [],
    name: 'getAllTasks',
    outputs: [ [Object] ],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x779900b4' },
  { inputs: [],
    name: 'getStatus',
    outputs: [ [Object] ],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x4e69d560' },
  { inputs: [ [Object] ],
    name: 'getTask',
    outputs: [ [Object] ],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x1d65e77e' },
  { inputs: [ [Object] ],
    name: 'status',
    outputs: [ [Object] ],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x42d21ef7' },
  { inputs: [ [Object] ],
    name: 'tasks',
    outputs:
     [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x8d977672' } ]


  export default new web3.eth.Contract(abi, address);

    